//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFSimuladorMaquina.WCFServicioRecicladoBotellas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contenedor", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioRecicladoBotellas.Entidades")]
    [System.SerializableAttribute()]
    public partial class Contenedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GramosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HoraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Gramos {
            get {
                return this.GramosField;
            }
            set {
                if ((this.GramosField.Equals(value) != true)) {
                    this.GramosField = value;
                    this.RaisePropertyChanged("Gramos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((this.HoraField.Equals(value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioRecicladoBotellas.Entidades")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServicioRecicladoBotellas.IServicioRecicladoBotellas")]
    public interface IServicioRecicladoBotellas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRecicladoBotellas/DoWork", ReplyAction="http://tempuri.org/IServicioRecicladoBotellas/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRecicladoBotellas/DoWork", ReplyAction="http://tempuri.org/IServicioRecicladoBotellas/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRecicladoBotellas/SelectContenedor", ReplyAction="http://tempuri.org/IServicioRecicladoBotellas/SelectContenedorResponse")]
        WPFSimuladorMaquina.WCFServicioRecicladoBotellas.Contenedor[] SelectContenedor(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRecicladoBotellas/SelectContenedor", ReplyAction="http://tempuri.org/IServicioRecicladoBotellas/SelectContenedorResponse")]
        System.Threading.Tasks.Task<WPFSimuladorMaquina.WCFServicioRecicladoBotellas.Contenedor[]> SelectContenedorAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRecicladoBotellas/InsertContenedor", ReplyAction="http://tempuri.org/IServicioRecicladoBotellas/InsertContenedorResponse")]
        int InsertContenedor(double gramos, System.DateTime fecha, System.TimeSpan hora, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRecicladoBotellas/InsertContenedor", ReplyAction="http://tempuri.org/IServicioRecicladoBotellas/InsertContenedorResponse")]
        System.Threading.Tasks.Task<int> InsertContenedorAsync(double gramos, System.DateTime fecha, System.TimeSpan hora, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRecicladoBotellas/SelectUsuario", ReplyAction="http://tempuri.org/IServicioRecicladoBotellas/SelectUsuarioResponse")]
        WPFSimuladorMaquina.WCFServicioRecicladoBotellas.Usuario SelectUsuario(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRecicladoBotellas/SelectUsuario", ReplyAction="http://tempuri.org/IServicioRecicladoBotellas/SelectUsuarioResponse")]
        System.Threading.Tasks.Task<WPFSimuladorMaquina.WCFServicioRecicladoBotellas.Usuario> SelectUsuarioAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRecicladoBotellas/GetUserMessage", ReplyAction="http://tempuri.org/IServicioRecicladoBotellas/GetUserMessageResponse")]
        string GetUserMessage(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRecicladoBotellas/GetUserMessage", ReplyAction="http://tempuri.org/IServicioRecicladoBotellas/GetUserMessageResponse")]
        System.Threading.Tasks.Task<string> GetUserMessageAsync(string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioRecicladoBotellasChannel : WPFSimuladorMaquina.WCFServicioRecicladoBotellas.IServicioRecicladoBotellas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRecicladoBotellasClient : System.ServiceModel.ClientBase<WPFSimuladorMaquina.WCFServicioRecicladoBotellas.IServicioRecicladoBotellas>, WPFSimuladorMaquina.WCFServicioRecicladoBotellas.IServicioRecicladoBotellas {
        
        public ServicioRecicladoBotellasClient() {
        }
        
        public ServicioRecicladoBotellasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioRecicladoBotellasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRecicladoBotellasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRecicladoBotellasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public WPFSimuladorMaquina.WCFServicioRecicladoBotellas.Contenedor[] SelectContenedor(string codigo) {
            return base.Channel.SelectContenedor(codigo);
        }
        
        public System.Threading.Tasks.Task<WPFSimuladorMaquina.WCFServicioRecicladoBotellas.Contenedor[]> SelectContenedorAsync(string codigo) {
            return base.Channel.SelectContenedorAsync(codigo);
        }
        
        public int InsertContenedor(double gramos, System.DateTime fecha, System.TimeSpan hora, string codigo) {
            return base.Channel.InsertContenedor(gramos, fecha, hora, codigo);
        }
        
        public System.Threading.Tasks.Task<int> InsertContenedorAsync(double gramos, System.DateTime fecha, System.TimeSpan hora, string codigo) {
            return base.Channel.InsertContenedorAsync(gramos, fecha, hora, codigo);
        }
        
        public WPFSimuladorMaquina.WCFServicioRecicladoBotellas.Usuario SelectUsuario(string codigo) {
            return base.Channel.SelectUsuario(codigo);
        }
        
        public System.Threading.Tasks.Task<WPFSimuladorMaquina.WCFServicioRecicladoBotellas.Usuario> SelectUsuarioAsync(string codigo) {
            return base.Channel.SelectUsuarioAsync(codigo);
        }
        
        public string GetUserMessage(string codigo) {
            return base.Channel.GetUserMessage(codigo);
        }
        
        public System.Threading.Tasks.Task<string> GetUserMessageAsync(string codigo) {
            return base.Channel.GetUserMessageAsync(codigo);
        }
    }
}
