//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASimuladorSiu.WCFRecicladoBotellas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFRecicladoBotellas.IServicioRecicladoBotellas")]
    public interface IServicioRecicladoBotellas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRecicladoBotellas/DoWork", ReplyAction="http://tempuri.org/IServicioRecicladoBotellas/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioRecicladoBotellas/DoWork", ReplyAction="http://tempuri.org/IServicioRecicladoBotellas/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioRecicladoBotellasChannel : WASimuladorSiu.WCFRecicladoBotellas.IServicioRecicladoBotellas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRecicladoBotellasClient : System.ServiceModel.ClientBase<WASimuladorSiu.WCFRecicladoBotellas.IServicioRecicladoBotellas>, WASimuladorSiu.WCFRecicladoBotellas.IServicioRecicladoBotellas {
        
        public ServicioRecicladoBotellasClient() {
        }
        
        public ServicioRecicladoBotellasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioRecicladoBotellasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRecicladoBotellasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRecicladoBotellasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
